[theme]
base = "dark"
primaryColor = "#a3e635"
backgroundColor = "#0a0c0a"
secondaryBackgroundColor = "#12141a"
textColor = "#e7ecef"
font = "sans serif"

[server]
headless = false

[browser]
gatherUsageStats = false
